# Generated by Django 3.2.4 on 2021-06-03 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 9, 32, 49, 38307)),
        ),
        migrations.AddField(
            model_name='data',
            name='num',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
