# Generated by Django 3.2.4 on 2021-06-03 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.FileField(default=None, upload_to=None),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 9, 56, 26, 580987)),
        ),
    ]
