# Generated by Django 3.2.4 on 2021-06-03 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20210603_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 10, 8, 39, 132408)),
        ),
    ]
