# Generated by Django 3.2.4 on 2021-06-03 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20210603_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 12, 33, 28, 844508)),
        ),
    ]
