# Generated by Django 3.2.4 on 2021-06-03 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_alter_planta_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 13, 27, 10, 363529)),
        ),
    ]
