# Generated by Django 3.2.4 on 2021-06-03 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_alter_planta_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='num',
        ),
        migrations.AddField(
            model_name='planta',
            name='species',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='planta',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 13, 47, 20, 644023)),
        ),
    ]
