# Generated by Django 3.2.4 on 2021-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_alter_planta_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='species',
            field=models.CharField(max_length=300),
        ),
    ]
