# Generated by Django 3.2.4 on 2021-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_alter_planta_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='image',
            field=models.FileField(blank=True, default='Images/planta.png', upload_to='Images'),
        ),
    ]
