# Generated by Django 3.2.4 on 2021-06-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_alter_planta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='image',
            field=models.FileField(blank=True, default='Images/planta.png', upload_to=''),
        ),
    ]
