# Generated by Django 3.2.4 on 2021-06-06 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_alter_planta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 6)),
        ),
    ]
