# Generated by Django 3.2.4 on 2021-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0025_alter_planta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='image',
            field=models.ImageField(blank=True, default='Images/planta.png', null=True, upload_to='Images'),
        ),
    ]
