# Generated by Django 3.2.4 on 2021-06-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0032_alter_planta_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='image',
            field=models.ImageField(blank=True, default='planta.png', null=True, upload_to='Images'),
        ),
    ]
