# Generated by Django 3.2.4 on 2021-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0034_planta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='image',
            field=models.FileField(blank=True, default='planta.png', null=True, upload_to='Images'),
        ),
    ]
