# Generated by Django 3.2.4 on 2021-06-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0035_alter_planta_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='user',
            new_name='usuario',
        ),
    ]
