# Generated by Django 3.2.4 on 2021-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0037_alter_planta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
