# Generated by Django 3.2.4 on 2021-06-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0038_alter_planta_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='name',
            field=models.CharField(error_messages={'message': 'Nome já adicionado'}, max_length=300, unique=True),
        ),
    ]
