# Generated by Django 3.2.4 on 2021-06-09 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0039_alter_planta_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='incidencia_solar',
            field=models.CharField(default='Sem dados', max_length=256),
        ),
        migrations.AddField(
            model_name='planta',
            name='temperatura',
            field=models.CharField(default='Sem dados', max_length=256),
        ),
        migrations.AddField(
            model_name='planta',
            name='umidade',
            field=models.CharField(default='Sem dados', max_length=256),
        ),
        migrations.AlterField(
            model_name='planta',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 9)),
        ),
        migrations.AlterField(
            model_name='planta',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
