# Generated by Django 3.2.4 on 2021-06-19 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0040_auto_20210609_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='BD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comum', models.CharField(max_length=256)),
                ('nome_especie', models.CharField(max_length=256)),
                ('temperatura', models.CharField(default='25 °C', max_length=30)),
                ('sol_horas', models.IntegerField(default=1)),
                ('rega_dias', models.IntegerField(default=1)),
                ('obs', models.CharField(default='Sem informações adicionais', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='planta',
            name='regada',
            field=models.DateField(default=datetime.date(2021, 6, 19)),
        ),
        migrations.AlterField(
            model_name='planta',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 19)),
        ),
    ]
