# Generated by Django 3.2.4 on 2021-06-24 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0041_auto_20210619_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 24)),
        ),
        migrations.AlterField(
            model_name='planta',
            name='regada',
            field=models.DateField(default=datetime.date(2021, 6, 24)),
        ),
    ]
